### DISCUSSION TITLE
Trigger Node-RED from a cover template in Home Assistant with Arguments

### DISCUSSION THREAD

**Discussion by mstuij** [zachowj/hass-node-red#48] [General]
Hi @zachowj 

I'm using your component for calling Node-RED from Home Assistant.

This works well for something were no arguments are necessary.

But in my Cover Template I have to pass arguments like the position. This is not working. Do you know some solution for this?

`cover:
  - platform: template
    covers:
      safe_test_cover:
        device_class: shutter
        friendly_name: "SAFE test cover"
        position_template: "{{ state_attr('cover.05_hal_1e_etage', 'current_position' ) | int }}"
        open_cover:
          service: cover.open_cover
          data:
            entity_id: cover.05_hal_1e_etage
        close_cover:
          service: nodered.trigger
          data:
            entity_id: switch.safe_close_cover_slowly
        stop_cover:
          service: cover.stop_cover
          data:
            entity_id: cover.05_hal_1e_etage
        set_cover_position:
          service: nodered.trigger
          data_template:
            entity_id: switch.safe_set_cover_position_slowly
            position: "{{position | int}}"
            currentposition: "{{ state_attr('cover.05_hal_1e_etage', 'current_position' ) | int }}"
`

So the close cover is working correctly.

The set_cover_position doesn't works. When I change my slider of the cover I get the error message:

Extra keys not allowed @data['position']

**Comment by zachowj** [comment]
The data you want to pass to the payload of the node should be in `payload`

Something like

```yaml
set_cover_position:
  service: nodered.trigger
  data_template:
  entity_id: switch.safe_set_cover_position_slowly
  payload:
    position: "{{position | int}}"
    currentposition: "{{ state_attr('cover.05_hal_1e_etage', 'current_position' ) | int }}"
```
