### ISSUE TITLE
No Nodered.trigger in HA

### ISSUE THREAD

**Issue by nickwild-999** [zachowj/hass-node-red#119]
## Version of the custom_component
Node Red companion v1.06

## Configuration

```
certfile: fullchain.pem
credential_secret: If1C7h!IL
http_node:
  password: ''
  username: ''
http_static:
  password: ''
  username: ''
init_commands: []
keyfile: privkey.pem
npm_packages: []
ssl: false
system_packages: []
theme: default
require_ssl: true
```

Logs
```
Welcome to Node-RED
===================
9 Feb 10:29:07 - [info] Node-RED version: v2.2.0
9 Feb 10:29:07 - [info] Node.js  version: v16.13.2
9 Feb 10:29:07 - [info] Linux 5.10.91 x64 LE
2022/02/09 10:29:08 [error] 561#561: *71 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "192.168.1.247:8123"
9 Feb 10:29:08 - [info] Loading palette nodes
2022/02/09 10:29:10 [error] 561#561: *71 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "192.168.1.247:8123"
2022/02/09 10:29:12 [error] 561#561: *71 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "GET /comms HTTP/1.1", upstream: "http://127.0.0.1:46836/comms", host: "192.168.1.247:8123"
9 Feb 10:29:13 - [info] Dashboard version 3.1.5 started at /endpoint/ui
BAIL ON node-red-node-pi-gpio/rpi-gpio
9 Feb 10:29:14 - [info] Settings file  : /etc/node-red/config.js
9 Feb 10:29:14 - [info] Context store  : 'default' [module=memory]
9 Feb 10:29:14 - [info] User directory : /config/node-red/
9 Feb 10:29:14 - [warn] Projects disabled : editorTheme.projects.enabled=false
9 Feb 10:29:14 - [info] Flows file     : /config/node-red/flows.json
9 Feb 10:29:14 - [info] Server now running at http://127.0.0.1:46836/
9 Feb 10:29:14 - [info] Starting flows
9 Feb 10:29:15 - [info] [mqtt-broker:b0272c16.53133] Connected to broker: mqtt://localhost:1883
9 Feb 10:29:19 - [info] [server:Home Assistant] Connecting to http://supervisor/core
9 Feb 10:29:19 - [info] [server:Home Assistant] Connected to http://supervisor/core

```

## Describe the bug
I am not getting a nodered.trigger service. I have set up a switch in NR using HomeAssistant, but still no joy. any thoughts please?

<img width="770" alt="Screenshot 2022-02-09 at 10 41 04" src="https://user-images.githubusercontent.com/18244022/153182267-b4575145-203a-4f20-b318-5d04f04a8936.png">
