### ISSUE TITLE
How to trigger nodes with multiple payloads in v3.0.0

### ISSUE THREAD

**Issue by popy2k14** [zachowj/hass-node-red#215]
## Version of the custom_component

3.0.0

## Configuration

This was working < 3.0.0

```
service: nodered.trigger
data:
  payload:
    type: 'announce'
    text: 'Hallo, das ist ein Test!'
    volume: 35
    device: 'Wohnzimmer'
    duration: 4
target:
  entity_id: switch.alexa_say_something
```

## Describe the bug

Can't trigger nodes with multiple payloads after v3.0.0 update

## Debug log

output of connected debug:

```
27.9.2023, 19:15:17[node: debug 9](http://homeassistant.local:8123/api/hassio_ingress/5cIp5p9Zag5aPmJtQcunSTkM2RCIUd-qzUNTLfckqxE/#)
triggered : msg : Object
object
topic: "triggered"
_msgid: "ded8f6093d77f23d"
```

the values are missing.

**Comment by zachowj** [comment]
Version 3.0.0 had a breaking change for the trigger service. It now only has two optional properties: `message` and `output_path`.

```
service: nodered.trigger
data:
  message:
    payload:
      type: 'announce'
      text: 'Hallo, das ist ein Test!'
      volume: 35
      device: 'Wohnzimmer'
      duration: 4
target:
  entity_id: switch.alexa_say_something
```
