### ISSUE TITLE
Stop work nodered.trigger after update

### ISSUE THREAD

**Issue by krasevych** [zachowj/hass-node-red#224]
## Version of the custom_component
latest, today updated

## Configuration

```yaml
  - type: image
    entity: light.cabinet_lights_left
    tap_action:
      action: call-service
      service: nodered.trigger
      service_data:
        entity_id: switch.gledopto_toggle
        payload:
          id: light.cabinet_lights_left
          brightness_on: 250
```

## Describe the bug

After update I see the error: `Call-service error. extra keys not allowed @ data['payload']`
## Debug log

```text

Call-service error. extra keys not allowed @ data['payload']

```

**Comment by zachowj** [comment]
https://github.com/zachowj/hass-node-red/releases/tag/v3.0.0

It was a breaking change in v3

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/custom_integration/exposed-nodes.html

```yaml
  - type: image
    entity: light.cabinet_lights_left
    tap_action:
      action: call-service
      service: nodered.trigger
      service_data:
        entity_id: switch.gledopto_toggle
        message:
          payload:
            id: light.cabinet_lights_left
            brightness_on: 250
```
