### ISSUE TITLE
Feature Request: Generate Virtual Switch for HASS 

### ISSUE THREAD

**Issue by Dodoooh** [zachowj/hass-node-red#4]
thanks for your work

Would it be possible to include the function to generate a virtual switch? 
This feature would be very great. Currently I'm doing it with virtual switch in HASS

**Comment by vajonam** [comment]
It already does this. 

https://community.home-assistant.io/t/node-red-contrib-home-assistant-websocket/71032/389?u=kermit

**Comment by Dodoooh** [comment]
Okay, sorry, I didn't know. 
But I need to customize the HASSIO config?  with the web hook ID? 
```
automation:
  trigger:
    platform: webhook
    webhook_id: some_hook_id
```
then it is almost easier and cleaner to create the virtual switches right in the config. 
or am I mistaking this?
