### ISSUE TITLE
followed instructions, node-red not appearing in integrations in Home Assistant Supervised version

### ISSUE THREAD

**Issue by mbariola** [zachowj/hass-node-red#44]
## Version of the custom_component

Using latest version from github

## Configuration

```yaml

Add your logs here.

```

Configuration:

```

homeassistant:
    customize: !include customize.yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# Example configuration.yaml entry
device_tracker: # Set consider_home to 1m to check / debug home presence
  - platform: bluetooth_le_tracker
  - platform: bluetooth_tracker
    request_rssi: true

```
customize.yaml:
```
device_tracker.oneplus_3t:
  friendly_name: Massi's OnePlus 3T
device_tracker.mi_smart_band_4:
  friendly_name: Massi's Mi Smart Band 4
light.80100865807d3a769f3b:
  supported_features: 63
```

```
Home Assistant v 0.116.4
arch | armv7l
-- | --
chassis |  
dev | false
docker | true
docker_version | 19.03.13
hassio | true
host_os | Raspbian GNU/Linux 10 (buster)
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 5.4.51-v7l+
python_version | 3.8.5
supervisor | 2020.10.0
timezone | Europe/Berlin
version | 0.116.4
virtualenv | false

```

## Describe the bug
Description:
I am using the Home Assistant Supervised Version (the one shipping with IOTStack). I followed the instructions in the readme file, creating the folders and downloading the files as instructed. This is the contents of the directory (filepath as seen from the host machine, mapping to the right /config folder within the homeassistant container)

```
/usr/share/hassio/homeassistant/custom_components/nodered $ ls -la
total 64
drwxr-xr-x 3 root root 4096 Oct 29 02:28 .
drwxr-xr-x 3 root root 4096 Oct 29 02:19 ..
-rw-r--r-- 1 root root 2072 Oct 29 02:28 binary_sensor.py
-rw-r--r-- 1 root root  983 Oct 29 02:28 config_flow.py
-rw-r--r-- 1 root root 1377 Oct 29 02:28 const.py
-rw-r--r-- 1 root root 3382 Oct 29 02:28 discovery.py
-rw-r--r-- 1 root root 7501 Oct 29 02:28 __init__.py
-rw-r--r-- 1 root root  328 Oct 29 02:28 manifest.json
-rw-r--r-- 1 root root 1172 Oct 29 02:28 sensor.py
-rw-r--r-- 1 root root  753 Oct 29 02:28 services.yaml
-rw-r--r-- 1 root root 4964 Oct 29 02:28 switch.py
drwxr-xr-x 2 root root 4096 Oct 29 02:28 translations
-rw-r--r-- 1 root root 4401 Oct 29 02:28 websocket.py

```
After restarting HA, when trying to add the integration, the integration is not present in the list.

## Debug log

Debug Logs:
```
Error sending through socket 18
3:32:22 AM – /usr/local/lib/python3.8/site-packages/zeroconf/__init__.py (WARNING)
You are using a custom integration for nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
3:31:09 AM – loader.py (WARNING)
Error setting up platform legacy
3:31:09 AM – Device tracker (ERROR)
No Bluetooth LE devices to track!
3:31:08 AM – bluetooth_le_tracker (WARNING)

```
