### ISSUE TITLE
Does not seem to work with modern home assistant

### ISSUE THREAD

**Issue by ReDetection** [zachowj/hass-node-red#47]
## Describe the bug

I recently updated Home Assistant to the modern version 2020.12.2 and unfortunately Node-Red companion integration stopped working, so my custom NodeRed entity went unavailable. Previous working version was 0.113.something

## Versions of the custom_component

hass-node-red custom_component: latest master (`739619e`)
home assistant core: 2020.12.2

## Debug log

I tried this logging config, no `nodered`/`node-red` occurrences appeared in logs :( 

```yaml
logger:
  default: info
  logs:
    custom_components.nodered: debug
```
